version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  scan:
    docker:
        - image: cimg/node:16.10
    environment:
        IMAGE_NAME: yy432/education-space
    steps:
        - checkout
        - setup_remote_docker      
        - docker/check
        - run: docker build -t $IMAGE_NAME .
        - snyk/scan: 
            docker-image-name: $IMAGE_NAME

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - build


            
