version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: yy432/education-space
          tag: 0.1.0
      - docker/push:
          image: yy432/education-space
          tag: 0.1.0
  
  deploy:
    docker:
        - image: cimg/node:16.10
    steps:
        - setup_remote_docker      
        - heroku/install
        - checkout
        - run:
            name: Heroku Container Push
            command: | 
                heroku container:login
                heroku container:push web -a yy432-su-devops
                heroku container:release web -a yy432-su-devops  

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      -  build-and-push:
          requires:
            - test
      - deploy:
          requires:
            - build-and-push
          filters:
            tags:
              only: /^v.*/
            
